### ISSUE TITLE
[FEAT] airflow 환경구성 & 예제 수행

### ISSUE THREAD

**Issue by kimkeonhyo** [kimkeonhyo/airflow-dev#4]
## What
- Airflow 환경구성
- gmail 연동 예제
- Task 순서 제어 예제

## Why
- Airflow 환경구성을 통해 Airflow를 연습해본다.
- 다양한 예제를 통해서 Airflow 숙련도를 높인다.

## To-Do
- [x] Airflow 환경 구성
- [x] Airflow Gmil 연동
- [x] Airflow Task 순서 제어
